### ISSUE TITLE
Error:  'module' object has no attribute 'vizsink_b'

### ISSUE THREAD

**Issue by jjmontesl** [CBrunsch/BinViz#1]
Hello.

I'm using BinViz from `master` on GNURadio 3.7.9 on Ubuntu 16.04

Build instructions work fine, and I can add the block to my workspace and configure it. However, when running the graph, I'm seeing:

```
Generating: '/home/jjmontes/Escritorio/top_block.py'

Executing: /usr/bin/python -u /home/jjmontes/Escritorio/top_block.py

Using Volk machine: avx_64_mmx_orc
Traceback (most recent call last):
  File "/home/jjmontes/Escritorio/top_block.py", line 224, in <module>
    main()
  File "/home/jjmontes/Escritorio/top_block.py", line 212, in main
    tb = top_block_cls()
  File "/home/jjmontes/Escritorio/top_block.py", line 159, in __init__
    self.binviz_vizsink_b_0 = binviz.vizsink_b(200, 100, "", "", "", False)
AttributeError: 'module' object has no attribute 'vizsink_b'
```

I have imported binviz from python and the module is found. The library however seems correclty installed:

```
jjmontes@jlaptop:~/git/BinViz/gr-binviz/build (master)$ sudo make install
[ 30%] Built target gnuradio-binviz
[ 80%] Built target test-binviz
[100%] Built target pygen_python_f91ec
[100%] Built target pygen_apps_9a6dd
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/cmake/binviz/binvizConfig.cmake
-- Up-to-date: /usr/local/include/binviz/api.h
-- Up-to-date: /usr/local/include/binviz/vizsink_b.h
-- Installing: /usr/local/lib/libgnuradio-binviz.so
-- Up-to-date: /usr/local/lib/python2.7/dist-packages/binviz/__init__.py
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/__init__.pyc
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/__init__.pyo
-- Up-to-date: /usr/local/share/gnuradio/grc/blocks/binviz_vizsink_b.xml
jjmontes@jlaptop:~/git/BinViz/gr-binviz/build (master)$ sudo ldconfig
```

Can you offer some advice? Thanks!

**Comment by jjmontesl** [comment]
![image](https://cloud.githubusercontent.com/assets/2786867/23822627/870d29bc-0650-11e7-8265-4bf48035cc51.png)

**Comment by CBrunsch** [comment]
Just made a fresh clone from the master branch... I cannot reproduce your issue.

```cbrunsch@tubarao:/Downloads/BinViz2/gr-binviz$ cd build/
cbrunsch@tubarao:/Downloads/BinViz2/gr-binviz/build$ cmake ..
-- The CXX compiler identification is GNU 4.8.4
-- The C compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Build type not specified: defaulting to release.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'cppunit'
--   found cppunit, version 1.13.1
-- Found CPPUNIT: /usr/lib/x86_64-linux-gnu/libcppunit.so;dl  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
Checking for GNU Radio Module: RUNTIME
-- checking for module 'gnuradio-runtime'
--   found gnuradio-runtime, version 3.7.9.2
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
-- Found GNURADIO_RUNTIME: /usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so  
GNURADIO_RUNTIME_FOUND = TRUE
-- 
-- Checking for module SWIG
-- Found SWIG version 2.0.11.
-- Found SWIG: /usr/bin/swig2.0  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.6", minimum required is "2") 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cbrunsch/Downloads/BinViz2/gr-binviz/build
cbrunsch@tubarao:/Downloads/BinViz2/gr-binviz/build$ make
Scanning dependencies of target gnuradio-binviz
[  5%] Building CXX object lib/CMakeFiles/gnuradio-binviz.dir/binimg.cc.o
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-binviz.dir/vizsink_b_impl.cc.o
Linking CXX shared library libgnuradio-binviz.so
[ 11%] Built target gnuradio-binviz
Scanning dependencies of target test-binviz
[ 16%] Building CXX object lib/CMakeFiles/test-binviz.dir/binimg.cc.o
[ 22%] Building CXX object lib/CMakeFiles/test-binviz.dir/test_binviz.cc.o
[ 27%] Building CXX object lib/CMakeFiles/test-binviz.dir/qa_binviz.cc.o
[ 33%] Building CXX object lib/CMakeFiles/test-binviz.dir/qa_vizsink_b.cc.o
Linking CXX executable test-binviz
[ 33%] Built target test-binviz
Scanning dependencies of target _binviz_swig_doc_tag
[ 38%] Building CXX object swig/CMakeFiles/_binviz_swig_doc_tag.dir/_binviz_swig_doc_tag.cpp.o
Linking CXX executable _binviz_swig_doc_tag
[ 38%] Built target _binviz_swig_doc_tag
Scanning dependencies of target binviz_swig_swig_doc
[ 44%] Generating doxygen xml for binviz_swig_doc docs
[ 50%] Generating python docstrings for binviz_swig_doc
[ 50%] Built target binviz_swig_swig_doc
Scanning dependencies of target _binviz_swig_swig_tag
[ 55%] Building CXX object swig/CMakeFiles/_binviz_swig_swig_tag.dir/_binviz_swig_swig_tag.cpp.o
Linking CXX executable _binviz_swig_swig_tag
[ 55%] Built target _binviz_swig_swig_tag
[ 61%] Generating binviz_swig.tag
Scanning dependencies of target binviz_swig_swig_2d0df
[ 66%] Building CXX object swig/CMakeFiles/binviz_swig_swig_2d0df.dir/binviz_swig_swig_2d0df.cpp.o
Linking CXX executable binviz_swig_swig_2d0df
Swig source
[ 66%] Built target binviz_swig_swig_2d0df
Scanning dependencies of target _binviz_swig
[ 72%] Building CXX object swig/CMakeFiles/_binviz_swig.dir/binviz_swigPYTHON_wrap.cxx.o
Linking CXX shared module _binviz_swig.so
[ 72%] Built target _binviz_swig
Scanning dependencies of target pygen_swig_cea7b
[ 77%] Generating binviz_swig.pyc
[ 83%] Generating binviz_swig.pyo
[ 83%] Built target pygen_swig_cea7b
Scanning dependencies of target pygen_python_2b31f
[ 88%] Generating __init__.pyc
[ 94%] Generating __init__.pyo
[ 94%] Built target pygen_python_2b31f
Scanning dependencies of target pygen_apps_9a6dd
[ 94%] Built target pygen_apps_9a6dd
Scanning dependencies of target doxygen_target
[100%] Generating documentation with doxygen
[100%] Built target doxygen_target
cbrunsch@tubarao:/Downloads/BinViz2/gr-binviz/build$ sudo make install
[ 11%] Built target gnuradio-binviz
[ 33%] Built target test-binviz
[ 38%] Built target _binviz_swig_doc_tag
[ 50%] Built target binviz_swig_swig_doc
[ 55%] Built target _binviz_swig_swig_tag
[ 66%] Built target binviz_swig_swig_2d0df
[ 72%] Built target _binviz_swig
[ 83%] Built target pygen_swig_cea7b
[ 94%] Built target pygen_python_2b31f
[ 94%] Built target pygen_apps_9a6dd
[100%] Built target doxygen_target
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/cmake/binviz/binvizConfig.cmake
-- Installing: /usr/local/include/binviz/api.h
-- Installing: /usr/local/include/binviz/vizsink_b.h
-- Installing: /usr/local/lib/libgnuradio-binviz.so
-- Removed runtime path from "/usr/local/lib/libgnuradio-binviz.so"
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/_binviz_swig.so
-- Removed runtime path from "/usr/local/lib/python2.7/dist-packages/binviz/_binviz_swig.so"
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/binviz_swig.py
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/binviz_swig.pyc
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/binviz_swig.pyo
-- Installing: /usr/local/include/binviz/binviz/swig/binviz_swig.i
-- Installing: /usr/local/include/binviz/binviz/swig/binviz_swig_doc.i
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/__init__.py
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/__init__.pyc
-- Installing: /usr/local/lib/python2.7/dist-packages/binviz/__init__.pyo
-- Installing: /usr/local/share/gnuradio/grc/blocks/binviz_vizsink_b.xml
-- Installing: /usr/local/share/doc/gr-binviz/xml
-- Installing: /usr/local/share/doc/gr-binviz/xml/namespacestd.xml
-- Installing: /usr/local/share/doc/gr-binviz/xml/vizsink__b_8h.xml
...
-- Installing: /usr/local/share/doc/gr-binviz/html/ftv2splitbar.png
-- Installing: /usr/local/share/doc/gr-binviz/html/nav_h.png
```
![image](https://cloud.githubusercontent.com/assets/5111303/24836768/03345728-1d25-11e7-8bc2-4813e9967b3d.png)

**Comment by bakroistvan** [comment]
This could be helpful: https://github.com/daniestevez/gr-outernet/issues/1
